import React, { useState, useEffect } from 'react'
import { Package, CheckCircle, RefreshCw, X, Check, Plus, Clock, AlertCircle } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
import { Button } from './ui/button'
import { Badge } from './ui/badge'
import { Input } from './ui/input'
import { LoadingSpinner } from './ui/loading'